### ISSUE TITLE
Slash commands randomly erroring with "unknown application command"

### ISSUE THREAD

**Issue by InfinityGhost** [InfinityGhost/TabletBot#44]
Slash commands randomly decided to quit working, eventually killed bot.
```
Discord.Net.HttpException: The server responded with error 10063: Unknown application command
    at Discord.Net.Queue.RequestBucket.SendAsync(RestRequest request)
    at Discord.Net.Queue.RequestQueue.SendAsync(RestRequest request)
    at Discord.API.DiscordRestApiClient.SendInternalAsync(String method, String endpoint, RestRequest request)
    at Discord.API.DiscordRestApiClient.SendAsync[TResponse](String method, String endpoint, BucketId bucketId, ClientBucketType clientBucket, RequestOptions options)
    at Discord.API.DiscordRestApiClient.DeleteGuildApplicationCommandAsync(UInt64 guildId, UInt64 commandId, RequestOptions options)
    at Discord.Rest.InteractionHelper.DeleteGuildCommandAsync(BaseDiscordClient client, UInt64 guildId, IApplicationCommand command, RequestOptions options)
    at Discord.Rest.RestGuildCommand.DeleteAsync(RequestOptions options)
    at TabletBot.Discord.SlashCommands.SlashCommandModule.Update(DiscordSocketClient client) in /root/src/TabletBot/TabletBot.Discord/SlashCommands/SlashCommandModule.cs:line 35
    at TabletBot.Discord.Bot.UpdateSlashCommands() in /root/src/TabletBot/TabletBot.Discord/Bot.Commands.cs:line 50
```

**Comment by InfinityGhost** [comment]
Appears to have resolved itself with dependency updates.
